[main]
include=/usr/share/foot/themes/catppuccin-mocha
font=VictorMono Nerd Font:size=11
font-bold=VictorMono Nerd Font:style=Bold:size=11
font-italic=VictorMono Nerd Font:style=Italic:size=11
font-bold-italic=VictorMono Nerd Font:style=Bold Italic:size=11

# Enable cursive italics if desired (Victor Mono features connected script italics)
pad=8x8
